<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["category", "Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Edit category</h1>
</div>

<?php echo $this->getContent(); ?>

<form action="category/save" class="form-horizontal" method="post">
    <div class="form-group">
    <label for="fieldChildCategory" class="col-sm-2 control-label">Child Of Category</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["child_category", "type" => "number", "class" => "form-control", "id" => "fieldChildCategory"]); ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldParentCategory" class="col-sm-2 control-label">Parent Of Category</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["parent_category", "type" => "number", "class" => "form-control", "id" => "fieldParentCategory"]); ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldName" class="col-sm-2 control-label">Name</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["name", "size" => 30, "class" => "form-control", "id" => "fieldName"]); ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCreateAt" class="col-sm-2 control-label">Create</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["create_at", "size" => 30, "class" => "form-control", "id" => "fieldCreateAt"]); ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUpdateAt" class="col-sm-2 control-label">Update</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["update_at", "size" => 30, "class" => "form-control", "id" => "fieldUpdateAt"]); ?>
    </div>
</div>


    <?php echo $this->tag->hiddenField("id") ?>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
        </div>
    </div>
</form>
