<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["category", "Go Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Create category</h1>
</div>

<?php echo $this->getContent(); ?>

<form action="category/create" class="form-horizontal" method="post">

<div class="form-group">
    <label for="fieldParentCategory" class="col-sm-2 control-label">Parent Of Category</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["parent_category", "type" => "number", "class" => "form-control", "id" => "fieldParentCategory"]); ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldName" class="col-sm-2 control-label">Name</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["name", "size" => 30, "class" => "form-control", "id" => "fieldName"]); ?>
    </div>
</div>




    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
        </div>
    </div>
</form>
