<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">

<?php echo $this->flash->output() ?>

    <?php
        foreach ($productsFiltered as $product) {
    ?>
            <div class="col-4 mt-2">
                <div class="card" style="width: 18rem;">
                    <img class="card-img-top img-fluid" src="<?php echo $product->picture_url ?>" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title"><?php echo $product->name ?></h5>
                        <p class="card-text"><?php echo $product->description ?></p>
                        <a href="#" class="btn btn-primary">Détail</a>
                    </div>
                </div>
            </div>
    <?php
        }
    ?>
</div>