<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["returned", "Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Edit returned</h1>
</div>

<?php echo $this->getContent(); ?>

<form action="returned/save" class="form-horizontal" method="post">
    <div class="form-group">
    <label for="fieldIdAccount" class="col-sm-2 control-label">Id Of Account</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id_account", "type" => "number", "class" => "form-control", "id" => "fieldIdAccount"]); ?>
    </div>
</div>




    <?php echo $this->tag->hiddenField("id") ?>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
        </div>
    </div>
</form>
