<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["delivery", "Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Edit delivery</h1>
</div>

<?php echo $this->getContent(); ?>

<form action="delivery/save" class="form-horizontal" method="post">
    <div class="form-group">
    <label for="fieldIdAccount" class="col-sm-2 control-label">Id Of Account</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id_account", "type" => "number", "class" => "form-control", "id" => "fieldIdAccount"]); ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldStatus" class="col-sm-2 control-label">Status</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["status", "size" => 30, "class" => "form-control", "id" => "fieldStatus"]); ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldEstimatedDate" class="col-sm-2 control-label">Estimated Of Date</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["estimated_date", "size" => 30, "class" => "form-control", "id" => "fieldEstimatedDate"]); ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDeliveryAt" class="col-sm-2 control-label">Delivery</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["delivery_at", "size" => 30, "class" => "form-control", "id" => "fieldDeliveryAt"]); ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCreateAt" class="col-sm-2 control-label">Create</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["create_at", "size" => 30, "class" => "form-control", "id" => "fieldCreateAt"]); ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUpdateAt" class="col-sm-2 control-label">Update</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["update_at", "size" => 30, "class" => "form-control", "id" => "fieldUpdateAt"]); ?>
    </div>
</div>


    <?php echo $this->tag->hiddenField("id") ?>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
        </div>
    </div>
</form>
