<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["account", "Go Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Create account</h1>
</div>

<?php echo $this->getContent(); ?>

<form action="account/create" class="form-horizontal" method="post">
    <div class="form-group">
    <label for="fieldUsername" class="col-sm-2 control-label">Username</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["username", "size" => 30, "class" => "form-control", "id" => "fieldUsername"]); ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPassword" class="col-sm-2 control-label">Password</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["password", "size" => 30, "class" => "form-control", "id" => "fieldPassword"]); ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldEmail" class="col-sm-2 control-label">Email</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["email", "size" => 30, "class" => "form-control", "id" => "fieldEmail"]); ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPhone" class="col-sm-2 control-label">Phone</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["phone", "size" => 30, "class" => "form-control", "id" => "fieldPhone"]); ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldRole" class="col-sm-2 control-label">Role</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["role", "type" => "number", "class" => "form-control", "id" => "fieldRole"]); ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldAddress" class="col-sm-2 control-label">Address</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["address", "size" => 30, "class" => "form-control", "id" => "fieldAddress"]); ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCreateAt" class="col-sm-2 control-label">Create</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["create_at", "size" => 30, "class" => "form-control", "id" => "fieldCreateAt"]); ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUpdateAt" class="col-sm-2 control-label">Update</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["update_at", "size" => 30, "class" => "form-control", "id" => "fieldUpdateAt"]); ?>
    </div>
</div>


    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
        </div>
    </div>
</form>
