<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["review", "Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Edit review</h1>
</div>

<?php echo $this->getContent(); ?>

<form action="review/save" class="form-horizontal" method="post">
    <div class="form-group">
    <label for="fieldIdProduct" class="col-sm-2 control-label">Id Of Product</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id_product", "type" => "number", "class" => "form-control", "id" => "fieldIdProduct"]); ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldIdAccount" class="col-sm-2 control-label">Id Of Account</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id_account", "type" => "number", "class" => "form-control", "id" => "fieldIdAccount"]); ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldComment" class="col-sm-2 control-label">Comment</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["comment", "size" => 30, "class" => "form-control", "id" => "fieldComment"]); ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldNbStar" class="col-sm-2 control-label">Nb Of Star</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["nb_star", "type" => "number", "class" => "form-control", "id" => "fieldNbStar"]); ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCreateAt" class="col-sm-2 control-label">Create</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["create_at", "size" => 30, "class" => "form-control", "id" => "fieldCreateAt"]); ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUpdateAt" class="col-sm-2 control-label">Update</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["update_at", "size" => 30, "class" => "form-control", "id" => "fieldUpdateAt"]); ?>
    </div>
</div>


    <?php echo $this->tag->hiddenField("id") ?>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
        </div>
    </div>
</form>
