<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>Search review</h1>
    <p><?php echo $this->tag->linkTo(["review/new", "Create review"]) ?></p>
</div>

<?php echo $this->getContent() ?>

<?php echo $this->flash->output() ?>

<form action="review/search" class="form-horizontal" method="get">
    <div class="form-group">
    <label for="fieldId" class="col-sm-2 control-label">Id</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id", "type" => "number", "class" => "form-control", "id" => "fieldId"]); ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldIdProduct" class="col-sm-2 control-label">Id Of Product</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id_product", "type" => "number", "class" => "form-control", "id" => "fieldIdProduct"]); ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldIdAccount" class="col-sm-2 control-label">Id Of Account</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id_account", "type" => "number", "class" => "form-control", "id" => "fieldIdAccount"]); ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldComment" class="col-sm-2 control-label">Comment</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["comment", "size" => 30, "class" => "form-control", "id" => "fieldComment"]); ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldNbStar" class="col-sm-2 control-label">Nb Of Star</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["nb_star", "type" => "number", "class" => "form-control", "id" => "fieldNbStar"]); ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCreateAt" class="col-sm-2 control-label">Create</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["create_at", "size" => 30, "class" => "form-control", "id" => "fieldCreateAt"]); ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUpdateAt" class="col-sm-2 control-label">Update</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["update_at", "size" => 30, "class" => "form-control", "id" => "fieldUpdateAt"]); ?>
    </div>
</div>


    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
        </div>
    </div>
</form>
