<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["product", "Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Edit product</h1>
</div>

<?php echo $this->getContent(); ?>

<form action="product/save" class="form-horizontal" method="post">
    <div class="form-group">
    <label for="fieldIdOwner" class="col-sm-2 control-label">Id Of Owner</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id_owner", "type" => "number", "class" => "form-control", "id" => "fieldIdOwner"]); ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldIdSubCategory" class="col-sm-2 control-label">Id Of Sub Of Category</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id_sub_category", "type" => "number", "class" => "form-control", "id" => "fieldIdSubCategory"]); ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldName" class="col-sm-2 control-label">Name</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["name", "size" => 30, "class" => "form-control", "id" => "fieldName"]); ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDescription" class="col-sm-2 control-label">Description</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["description", "size" => 30, "class" => "form-control", "id" => "fieldDescription"]); ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldStock" class="col-sm-2 control-label">Stock</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["stock", "type" => "number", "class" => "form-control", "id" => "fieldStock"]); ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPictureUrl" class="col-sm-2 control-label">Picture Of Url</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["picture_url", "size" => 30, "class" => "form-control", "id" => "fieldPictureUrl"]); ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCreateAt" class="col-sm-2 control-label">Create</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["create_at", "size" => 30, "class" => "form-control", "id" => "fieldCreateAt"]); ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUpdateAt" class="col-sm-2 control-label">Update</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["update_at", "size" => 30, "class" => "form-control", "id" => "fieldUpdateAt"]); ?>
    </div>
</div>


    <?php echo $this->tag->hiddenField("id") ?>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
        </div>
    </div>
</form>
