<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["product/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["product/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
            <th>Id Of Owner</th>
            <th>Id Of Sub Of Category</th>
            <th>Name</th>
            <th>Description</th>
            <th>Stock</th>
            <th>Picture Of Url</th>
            <th>Create</th>
            <th>Update</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->getItems() as $product): ?>
            <tr>
            <td><?php echo $product['id']; ?></td>
            <td><?php echo $product['id_owner']; ?></td>
            <td><?php echo $product['id_sub_category']; ?></td>
            <td><?php echo $product['name']; ?></td>
            <td><?php echo $product['description']; ?></td>
            <td><?php echo $product['stock']; ?></td>
            <td><?php echo $product['picture_url']; ?></td>
            <td><?php echo $product['create_at']; ?></td>
            <td><?php echo $product['update_at']; ?></td>

                <td><?php echo $this->tag->linkTo(["product/page/" . $product['id'], "Page"]); ?></td>
                <td><?php echo $this->tag->linkTo(["product/edit/" . $product['id'], "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["product/delete/" . $product['id'], "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->getCurrent(), "/", $page->getTotalItems() ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo(["product/search", "First", 'class' => 'page-link', 'id' => 'first']) ?></li>
                <li><?php echo $this->tag->linkTo(["product/search?page=" . $page->getPrevious(), "Previous", 'class' => 'page-link', 'id' => 'previous']) ?></li>
                <li><?php echo $this->tag->linkTo(["product/search?page=" . $page->getNext(), "Next", 'class' => 'page-link', 'id' => 'next']) ?></li>
                <li><?php echo $this->tag->linkTo(["product/search?page=" . $page->getLast(), "Last", 'class' => 'page-link', 'id' => 'last']) ?></li>
            </ul>
        </nav>
    </div>
</div>
